language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov"
script:
  - py.test --cov rasterio --cov-report geobricks_modis_test/core/test_modis_core.py
  - py.test --cov rasterio --cov-report geobricks_modis_test/rest/test_modis_rest.py
after_success:
  - coveralls